### ISSUE TITLE
how are the training images of Canon dataset generated?

### ISSUE THREAD

**Issue by nan-rock** [goutamgmb/deep-burst-sr#10]
Can you please tell me, how have you taken the training crops of size 448x448? Have you used cv2.resize to resize the images, as some of the images seem to be blurred to some extent? 
Where in the code, have you implemented this part of cropping?

**Comment by goutamgmb** [comment]
Hi,

The pre-processing code is not included in the repo since I haven't cleaned it up yet. To generate the training crops, we extract 160×160 crops from the burst images in a sliding window manner, with a stride of 80 pixels. For each crop, we again estimate homography between the crop and the corresponding region in DSLR image to perform local alignment. The aligned DSLR image region is then resized to 160*4 × 160*4 (using cv2 resize) to obtain the ground truth crop. 

In general, when collecting the data, we tried to set the focal length on the DSLR such that its zoom factor was ~4 compared to the phone camera. Thus, the resizing stage should not perform heavy upsampling.

Regards
Goutam
