### ISSUE TITLE
The checkpoints can not be loaded

### ISSUE THREAD

**Issue by greatlog** [goutamgmb/deep-burst-sr#17]
It seems that you have saved the structure of this directory into the checkpoints. However, the directory has been changed. The "local" module in the admin directory has been removed. Consequently, the checkpoints can not be properly loaded. Would you mind providing new checkpoints?

**Comment by goutamgmb** [comment]
Hi,

The local.py file is created automatically when you run the install.sh script. Otherwise you could manually run the following command to create the default local.py file.
python -c "from admin.environment import create_default_local_file; create_default_local_file()"
Please let me know if you still can't load checkpoints after creating the local.py file

**Comment by greatlog** [comment]
thanks.
